name: Data-from-info21c

on:
  push:
    tags:
      - "v*" # v로 시작하는 태그가 푸시될 때 트리거됩니다.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Install Windows Build Tools
        run: npm install --global windows-build-tools

      - name: Build Electron app
        run: npm run make

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/**/*.zip
            out/make/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
